### ISSUE TITLE
Security bug Report

### ISSUE THREAD

**Issue by CapBarbossa** [LDAPAccountManager/docker#1]
Hi, there. I've been using LAM docker with version `ldap-account-manager-8.5RC`. I found a bug:
If the master password to lam is changed to something different from the default `lam` string, say `123`, then after the container is restarted, this password is somehow reset to `lam`!
This seems a serious security issue if you expose lam to Internet. As a matter of fact, I am currently doing this.
Hope you guys notice this and fix it ASAP.

**Comment by gruberroland** [comment]
Did you set LAM_SKIP_PRECONFIGURE to true? Otherwise, LAM will apply the config as defined by the environment variables.

https://github.com/LDAPAccountManager/lam/blob/develop/lam-packaging/docker/.env

**Comment by CapBarbossa** [comment]
> Did you set LAM_SKIP_PRECONFIGURE to true? Otherwise, LAM will apply the config as defined by the environment variables.
> 
> https://github.com/LDAPAccountManager/lam/blob/develop/lam-packaging/docker/.env

No, I didn't. I didn't even know this env variable at all before. As an average user, I just use the command the developer of this software provide, how can I know these env variable details?  Anyway, thanks a lot for the kind hint.
To make others clear about this issue I met, here is my modified docker command with the hint provided:
```
docker run -dit --restart always  \
-e LAM_SKIP_PRECONFIGURE=true \
-p 12001:80 \
--name ldap-account-manager-8.5RC  \
ghcr.io/ldapaccountmanager/lam:stable
```
Now, the container can keep the password as expected.

**Comment by gruberroland** [comment]
The environment variables are documented here: https://github.com/LDAPAccountManager/docker
