### ISSUE TITLE
[rootless-podman] Possibility to let apache bind to another port?

### ISSUE THREAD

**Issue by TonyBostonTB** [LDAPAccountManager/docker#6]
We're testing LAM with rootless-podman here but having a hard time to get it to reach the openldap server that runs on the host system. We wanted to test with "--network=host" but as you might guess, its not possible to bind to port 80/tcp.

**Comment by TonyBostonTB** [comment]
The reason we're even trying this: our ldap server is TLS/SSL only but LAM can not connect to the host systems IP address unless we're using "ldap://host.containers.internal:389" which then of course results in LAM getting a tls error (error message is not very verbose but we'd assume its because the hostname doesnt match the certificate name)

**Comment by gruberroland** [comment]
Exactly, for LDAPS and LDAP+TLS (port 389) the certificate needs to match the hostname.

I cannot support much here as this is a configuration outside of LAM. But maybe you can add the LDAP IP with its domain name in /etc/hosts?

**Comment by TonyBostonTB** [comment]
You mean like so?
`10.10.10.10 ldap.example.com host.containers.internal`

**Comment by gruberroland** [comment]
Exactly

**Comment by TonyBostonTB** [comment]
Great, that worked. Thanks @gruberroland

**Comment by TonyBostonTB** [comment]
Great, that worked. Thanks @gruberroland
